version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src/api:/var/www/api/"
            - "./src/html:/var/www/html/"
        ports:
            - "80:80"
            - "3000:3000"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        container_name: php-container
        build: "docker/php/"
        restart: always
        volumes:
            - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./src:/var/www/"
        links: 
            - "mysqldb:mysqldb"        
    mysqldb:
        image: mysql:5.7
        container_name: mysql-container
        restart: always
        environment:   
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        command: --init-file /tmp/mysql/init.sql
        volumes:
            - "./docker/mysql/tmp:/tmp/mysql"